version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  lint:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: pip install black
          name: Install black
      - run:
          command: black --check .
          name: Run black
  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: make test
          name: Run tests

workflows:
  main:
    jobs:
      - lint
      - test
      - hold:
          type: approval
          requires:
            - lint
            - test
